### PR TITLE
use go get to get this project

### PR DESCRIPTION
**Pull request by DaidoujiChen**
Hello @metrue,

Tiny fix.

### CODE REVIEW

**Comment by metrue** [comment]
thanks @DaidoujiChen

**Comment by metrue** [comment]
@DaidoujiChen it seems like this PR broke the build. would you be nice to fix it?
https://circleci.com/gh/metrue/fx/108

**Comment by DaidoujiChen** [comment]
Let me check this.

**Comment by DaidoujiChen** [comment]
ok, it seems like your `glide` version too old.
I will fire a new pr for it.

**Pull request merged**
