### PR TITLE
Unify func of php && add func.php to examples

### PR DESCRIPTION
**Pull request by chlins**
Make it better ~~~

### CODE REVIEW

**Comment by metrue** [comment]
Thanks @chlins 

the other thing you need to take care is to update the `images-functionName` map in https://github.com/metrue/fx/blob/master/server/handlers/up.go#L21

**Comment by chlins** [comment]
Oh~~~yeah,i see that.

**Comment by metrue** [comment]
@chlins 

I am reviewing your PR right, I found that the php Dockerfile is not a web service, it just run a php script.

actually what we expect is everything function can become a accessable service, it means we can access the deployed function via url. 
for example: 

```
curl -X POST <service url> -H "Content-Type: application/json" -d '{"a": 1, "b": 1}'
```

**Comment by metrue** [comment]
@chlins 

basically, your PR make fx support php now. but when I try to test my  service (simple a+b function).
I get following error: 

```
$ http post 0.0.0.0:39151 a=1 b=1
HTTP/1.1 200 OK
Connection: close
Content-type: text/html; charset=UTF-8
Date: Sat, 18 Nov 2017 06:35:23 +0000
Host: 0.0.0.0:39151
X-Powered-By: PHP/7.1.11

<br />
<b>Warning</b>:  Illegal string offset 'a' in <b>/fx.php</b> on line <b>3</b><br />
<br />
<b>Warning</b>:  Illegal string offset 'b' in <b>/fx.php</b> on line <b>3</b><br />
```

**Comment by metrue** [comment]
@chlins 

it turns out I did not include your changes into image.zip (which is used in fx build and deploy)

Thanks a lot for your great PR.

**Pull request merged**
