### PR TITLE
Add rust base image for Rust

### PR DESCRIPTION
**Pull request by FrontMage**
Add rust support with Rocket.

### CODE REVIEW

**Comment by FrontMage** [comment]
Please do not merge just yet, the HTTP routing framework requires rust nightly build, which does not have official docker image, I'm trying to fix this by building a new public image.

**Comment by FrontMage** [comment]
Another problem is that rust needs its codes inside `src` directory, I can only expose the `fx.rs` by linking it to `src/fns/mod.rs`.

---

The image is OK now, I tested it.

**Comment by metrue** [comment]
Thanks @FrontMage 

But it seems like test not passed, I will check it later.

**Comment by FrontMage** [comment]
@metrue I think it's a bug in the base image, fixed it.

**Comment by metrue** [comment]
@FrontMage 

awesome, I will try it now.

**Comment by metrue** [comment]
And actually `fx` put all the base images code into `fx/assets` now, it would be great if you do so. 
I will do it after I verify everything is good anyway.

**Comment by FrontMage** [comment]
@metrue Files are moved to `assets/dockerfiles/base`.

**Comment by metrue** [comment]
@FrontMage  Cool. 

Will test it and merge, if everything is ok, will make a release soon.

**Comment by metrue** [comment]
@FrontMage 

base image for rust works well,  but if we want `fx` support `Rust`, we have extra work to do, I will keep you update in following PR.

**Pull request merged**
