### PR TITLE
WIP: add protoc installation script

### PR DESCRIPTION
**Pull request by metrue**
@muka 

I am trying to make the build process easier, please have review if you have time.

### CODE REVIEW

**Comment by metrue** [comment]
@muka 

I am checking your gist https://gist.github.com/muka/4cc42c478b2699f0969450a1ec1ce44c#file-install-protoc-sh-L19

I wonder why you have to rename the googleapi directory?
```
git clone https://github.com/googleapis/googleapis.git tmp/googleapis
mv tmp/googleapis/google/api/ google/
```

**Comment by metrue** [comment]
@muka 

Yeah, I already updated the script, but its still not good enough merge it into master. 

You can review and comment it anytime.

**Comment by metrue** [comment]
@muka 

I already merge it into master.

**Comment by muka** [comment]
Great work, I do not have a windows pc so I cannot help on supporting it there. 

If generation turn out to be problematic, we can remove it from `build` in Makefile and just keep the generated types in the repo

**Pull request merged**
