### PR TITLE
Use gRPC over websocket

### PR DESCRIPTION
**Pull request by muka**
This PR address #98 add protocol buffer based type integrated to the codebase. In this version the WS support has been replaced, let me know if may be useful to keep it.

Main changes are listed here

- `api` package has been renamed to `docker`
- `api/` now contains generated types and the service stub. 
- struct in `common/meta.go` and `message/*` has been ported to protobuf definitions and replaced in the code by those from `api/fx.proto`.
- `make generate` creates the code bundle implementing types and service / client
- `swagger/` folder contains the HTTP API definition. 
- gRPC listen on `:5000` while HTTP remained on port localhost:8080
- Unit test for up / down / list / serve
- Added setup example for the required dependencies of gRPC 

Feedback is welcome!

Thank you

### CODE REVIEW

**Comment by metrue** [comment]
@muka 

I am reviewing it, can you fix the CI build first ?

**Comment by muka** [comment]
Thanks, I have an issue with `dep` to be solved. Technically, need to learn how to use it..

**Comment by muka** [comment]
I have another PR with further unit test but requires some refactoring in `handler` and `docker-api`  to handle explicitly errors instead of panic-ing.

I would split the two to avoid a massive PR. I can also work there on docs coverage.

What do you think?

**Comment by metrue** [comment]
@muka 

Two PRs seems great, please go ahead.

**Comment by metrue** [comment]
it seems like protobuf and gRPC is not dep friendly, `dep ensure` could not make everything works out of box.  I have to do some manually `go get <some>`

**Comment by pplam** [comment]
@muka I encounter the following error:

➜  fx git:(gRPC) ✗ make build
google/api/annotations.proto: File not found.
fx.proto: Import "google/api/annotations.proto" was not found or had errors.
protoc-gen-grpc-gateway: program not found or is not executable
--grpc-gateway_out: protoc-gen-grpc-gateway: Plugin failed with status code 1.
protoc-gen-swagger: program not found or is not executable
--swagger_out: protoc-gen-swagger: Plugin failed with status code 1.
api/fx.go:1: running "sh": exit status 1
make: *** [generate] Error 1

The "google/api/annotations.proto" file seems to locate here:
github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api/annotations.proto

But when I change the reference to it, also not found. I don't know why.
I haven't set up my environment correctly？Could you tell me some why?

**Comment by muka** [comment]
Hi @pplam 
I tried to setup my environment again and wrote down the steps here (so maybe we can also add to CI)

https://gist.github.com/muka/4cc42c478b2699f0969450a1ec1ce44c

It will install the `protoc` compiler and also the required includes.

Once completed, `make generate` should work as expected.

**Comment by muka** [comment]
Hi @metrue, I'd say the PR is complete. The new API has an initial test support and passes. 

I do not know well `codecov` but looking at details of the failing check it show no meaningful hints on how to fix.

I also found those issues that may be relevant eventually

- https://github.com/codecov/support/issues/135
- https://github.com/fossasia/susper.com/issues/487

Let me know if it is ok for you and we can go further

Thanks

**Comment by pplam** [comment]
@muka Nice, It's clear! Your script figures out my problem:
The `googleapis` package wasn't installed correctly by `dep` on my machine

By fixing this then:
~~~
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
~~~
I now have make `make build` process pass, thank you! [ :tada: ][ :tada: ]

**Comment by metrue** [comment]
@muka 

I will test it out soon,  if no further issue, I should be able to merge it tonight. Thank you for you great work.

**Comment by metrue** [comment]
@muka 

Your PR merged to master already, everything work great, thanks  a lot for your great work.

**Comment by metrue** [comment]
@muka 

`fx down '*'` is not working since this merge, would you help take a look?

**Pull request merged**
