### PR TITLE
Move logger to outer

### PR DESCRIPTION
**Pull request by chlins**
Hey, metrue,i think log should not just in the up package, so i move it to outer for global manage.

### CODE REVIEW

**Comment by metrue** [comment]
thanks @chlins

**Comment by metrue** [comment]
@chlins Build broken after merge your PR, would you be nice to help fix ?

**Comment by chlins** [comment]
Ok~~~i see

**Comment by chlins** [comment]
Yes,it's my carelessness,sorry,i will fix it.

**Comment by metrue** [comment]
@chlins 

it still fail, v^v

**Comment by metrue** [comment]
I fixed it already, thanks.

**Pull request merged**
